In [32]:
import lightgbm as lgb
import pandas as pd

In [33]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [34]:
cols = [
    'pts', 'ptspg', 'fgm', 'fga', 'fgp', '3pm',
    '3pa', '3pp', 'ftm', 'fta', 'ftp',
    'orb', 'orbpg', 'drb', 'drbpg', 'reb',
    'rebpg', 'ast', 'astpg', 'stl', 'stlpg',
    'blk', 'blkpg', 'tov', 'tovpg', 'pf',
    'pfpg', 'seed', 'wins', 'losses', 'winp',
    'cwins', 'closses', 'cwinp'
]

In [35]:
all_data = pd.read_csv('data/all_data.csv').dropna()

In [36]:
train = all_data[all_data.year != 2023]
test = all_data[all_data.year == 2023]
model_cols = [f'{col}_diff' for col in cols]

x_train, y_train = train[model_cols], train['winner']
x_test, y_test = test[model_cols], test['winner']

model.fit(x_train, y_train)
test['pred'] = model.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(test.winner, test.pred)
print(accuracy)

0.7611940298507462

/home/trevor/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/tmp/ipykernel_6064/53874162.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test['pred'] = model.predict(x_test)

In [37]:
test[['team0', 'team1', 'winner', 'pred']].tail(50)

                  team0                team1  winner  pred
1199          Creighton            Princeton       0     1
1200    San Diego State            Creighton       0     0
1201            Houston    Northern Kentucky       0     0
1202               Iowa               Auburn       1     1
1203         Miami (FL)                Drake       0     0
1204            Indiana           Kent State       0     1
1205         Iowa State           Pittsburgh       1     0
1206             Xavier       Kennesaw State       0     0
1207          Texas A&M           Penn State       1     1
1208              Texas              Colgate       0     0
1209            Houston               Auburn       0     0
1210            Indiana           Miami (FL)       1     1
1211             Xavier           Pittsburgh       0     0
1212              Texas           Penn State       0     0
1213            Houston           Miami (FL)       1     0
1214              Texas               Xavier       0     0
1215              Texas           Miami (FL)       1     1
1216             Purdue  Fairleigh Dickinson       1     0
1217            Memphis    Florida Atlantic        1     1
1218               Duke         Oral Roberts       0     0
1219          Tennessee            Louisiana       0     0
1220           Kentucky           Providence       0     0
1221       Kansas State        Montana State       0     0
1222     Michigan State                  USC       0     0
1223          Marquette              Vermont       0     0
1224  Florida Atlantic   Fairleigh Dickinson       0     0
1225          Tennessee                 Duke       0     1
1226       Kansas State             Kentucky       0     0
1227          Marquette       Michigan State       1     0
1228          Tennessee    Florida Atlantic        1     1
1229       Kansas State       Michigan State       0     0
1230       Kansas State    Florida Atlantic        1     1
1231             Kansas               Howard       0     0
1232           Arkansas             Illinois       0     0
1233       Saint Mary's                  VCU       0     0
1234              UConn                 Iona       0     0
1235                TCU        Arizona State       0     0
1236            Gonzaga         Grand Canyon       0     0
1237       Northwestern          Boise State       0     0
1238               UCLA        UNC Asheville       0     0
1239             Kansas             Arkansas       1     0
1240              UConn         Saint Mary's       0     0
1241            Gonzaga                  TCU       0     0
1242               UCLA         Northwestern       0     0
1243              UConn             Arkansas       0     0
1244               UCLA              Gonzaga       1     0
1245            Gonzaga                UConn       1     1
1246    San Diego State    Florida Atlantic        0     1
1247         Miami (FL)                UConn       1     1
1248              UConn      San Diego State       0     0

In [38]:
test[test.winner != test.pred]

,year,team0,team1,region,round,winner,pts_team0,ptspg_team0,fgm_team0,fga_team0,...,pf_diff,pfpg_diff,seed_diff,wins_diff,losses_diff,winp_diff,cwins_diff,closses_diff,cwinp_diff,pred
1183,2023,Pittsburgh,Mississippi State,none,0,0,2512.0,76.121,868.0,1916.0,...,37.0,1.121,0.0,2.0,-2.0,0.061,6.0,-4.0,0.256,1
1189,2023,Virginia,Furman,South Regional,1,1,2170.0,67.812,769.0,1711.0,...,-112.0,-2.453,-9.0,-4.0,2.0,-0.074,0.0,2.0,-0.083,0
1190,2023,Creighton,NC State,South Regional,1,0,2529.0,76.636,908.0,1943.0,...,-140.0,-4.242,-5.0,-1.0,1.0,-0.030,2.0,-2.0,0.100,1
1193,2023,Arizona,Princeton,South Regional,1,1,2811.0,82.676,999.0,2015.0,...,108.0,0.788,-13.0,4.0,1.0,0.001,4.0,2.0,-0.014,0
1196,2023,Baylor,Creighton,South Regional,2,1,2469.0,77.156,823.0,1843.0,...,122.0,4.223,-3.0,-1.0,0.0,-0.011,-3.0,1.0,-0.089,0
1197,2023,Missouri,Princeton,South Regional,2,1,2623.0,79.485,936.0,1978.0,...,127.0,1.880,-8.0,0.0,4.0,-0.096,1.0,3.0,-0.103,0
1199,2023,Creighton,Princeton,South Regional,3,0,2529.0,76.636,908.0,1943.0,...,-37.0,-3.089,-9.0,-1.0,5.0,-0.126,4.0,2.0,-0.014,1
1204,2023,Indiana,Kent State,Midwest Regional,1,0,2476.0,75.030,939.0,1918.0,...,-75.0,-1.696,-9.0,-7.0,6.0,-0.188,-3.0,5.0,-0.233,1
1205,2023,Iowa State,Pittsburgh,Midwest Regional,1,1,2190.0,68.438,820.0,1822.0,...,75.0,2.852,-5.0,-5.0,4.0,-0.135,-5.0,3.0,-0.200,0
1213,2023,Houston,Miami (FL),Midwest Regional,3,1,2551.0,75.029,936.0,2028.0,...,102.0,2.153,-4.0,3.0,-1.0,0.038,2.0,-4.0,0.194,0
1216,2023,Purdue,Fairleigh Dickinson,East Regional,1,1,2485.0,73.088,865.0,1883.0,...,-181.0,-5.323,-15.0,7.0,-7.0,0.206,5.0,-1.0,0.125,0
1225,2023,Tennessee,Duke,East Regional,2,0,2369.0,71.788,843.0,1931.0,...,36.0,1.552,-1.0,-4.0,3.0,-0.098,-3.0,1.0,-0.089,1
1227,2023,Marquette,Michigan State,East Regional,2,1,2718.0,79.941,1007.0,2066.0,...,41.0,-0.251,-5.0,7.0,-4.0,0.149,6.0,-5.0,0.271,0
1239,2023,Kansas,Arkansas,West Regional,2,1,2548.0,74.941,940.0,2019.0,...,-68.0,-2.562,-7.0,5.0,-4.0,0.129,5.0,-5.0,0.278,0
1244,2023,UCLA,Gonzaga,West Regional,3,1,2513.0,73.912,949.0,2071.0,...,-21.0,-1.112,-1.0,0.0,1.0,-0.024,4.0,0.0,0.025,0
1246,2023,San Diego State,Florida Atlantic,none,5,0,2378.0,72.061,838.0,1886.0,...,-7.0,0.268,-4.0,-6.0,5.0,-0.152,-3.0,1.0,-0.067,1